version: '3'

services:
  db:
    image: alpine
    container_name: sqlite_db
    restart: always
    stdin_open: true
    tty: true
    command: sh -c 'apk add --no-cache sqlite && exec sqlite3 /data/database.db'